@startuml diagramme-edit

Browser->Nuxeo: 
Nuxeo->Browser: html page with buttons

...
note over Browser: user clicks on "Live edit"

Browser->Nuxeo: .../site/onlyoffice/edit/42
Nuxeo -> Browser: html with OnlyOffice config :\n  url: ".../site/onlyoffice/download/42?sessionToken=xyz"\n  callbackUrl: ".../site/onlyoffice/callbackEdit/42?sessionToken=xyz"
    
Browser -> OnlyOffice
OnlyOffice -> Nuxeo : .../site/onlyoffice/download/42?sessionToken=xyz
Nuxeo -> OnlyOffice : initial content
OnlyOffice -> Browser : displays document

...
note over Browser : user modifies the document
Browser <-> OnlyOffice :
...

note over Browser : user finishes editing
Browser -> OnlyOffice :
OnlyOffice -> Browser : redirect to nuxeo
Browser -> Nuxeo :
Nuxeo -> Browser : nuxeo user interface

...
note over OnlyOffice : a few seconds later
OnlyOffice -> Nuxeo : .../site/onlyoffice/callbackEdit/42?sessionToken=xyz with\n  status: 2\n  url: ".../abc"
Nuxeo -> OnlyOffice
Nuxeo -> OnlyOffice : .../abc
OnlyOffice -> Nuxeo : modified content
note over Nuxeo : saves the document

@enduml
